[package]

name = "quantified_self"
version = "0.0.1"
authors = ["bbodi <sharp1113@hotmail.com.com>"]

[dependencies.imgui]
path = "../imgui/"

# [dependencies.postgres]
# git = "https://github.com/sfackler/rust-postgres.git"

[profile.release]
opt-level = 3
debug = false